use game_store;

create table if not exists users(
                                                                                                                                                                                                                                       	username varchar(50) not null primary key,
                                                                                                                                                                                                                                       	password varchar(100) not null,
                                                                                                                                                                                                                                       	enabled boolean not null
                                                                                                                                                                                                                                       );

                                                                                                                                                                                                                                       create table if not exists authorities (
                                                                                                                                                                                                                                       	username varchar(50) not null,
                                                                                                                                                                                                                                       	authority varchar(50) not null,
                                                                                                                                                                                                                                       	constraint fk_authorities_users foreign key(username) references users(username));
                                                                                                                                                                                                                                       	create unique index ix_auth_username on authorities (username,authority
                                                                                                                                                                                                                                       );

                                                                                                                                                                                                                                       insert into users (username, password, enabled) values ('user', '$2a$10$IMVK/bDgQPYk3QCHpfxxQ.Nph28JZV9dnwI5kzKam1Zm0d2tkEteW', true);
                                                                                                                                                                                                                                       insert into users (username, password, enabled) values ('staff', '$2a$10$TiWUXLofAvbUBLHle5FuAegD/LqFtwq9ZX711bPaga.UoK0G3h9hO', true);
                                                                                                                                                                                                                                       insert into users (username, password, enabled) values ('manager', '$2a$10$poWtYIqZ86rw7.ERTLrQOO4Qy.8vYeeFs4GlIkRrcdkYggR0wOcRq', true);
                                                                                                                                                                                                                                       insert into users (username, password, enabled) values ('admin', '$2a$10$Boi.SzoOXjVJ/a6Z/3TsmeNy/ALEXTGiarNsreMi7BR7F58vaCLpm', true);


                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('user', 'ROLE_USER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('staff', 'ROLE_USER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('staff', 'ROLE_STAFF');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('manager', 'ROLE_USER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('manager', 'ROLE_STAFF');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('manager', 'ROLE_MANAGER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('admin', 'ROLE_USER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('admin', 'ROLE_STAFF');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('admin', 'ROLE_MANAGER');
                                                                                                                                                                                                                                       insert into authorities (username, authority) values ('admin', 'ROLE_ADMIN');